In [25]:
import pandas as pd
import numpy as np

In [26]:
# Question 1
# What's the version of Pandas that you installed?

In [27]:
pd.__version__

'1.5.3'

In [28]:
df = pd.read_csv('housing.csv') 

In [29]:
# Question 2
# How many columns are in the dataset?

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [31]:
# Question 3
# Which columns in the dataset have missing values?

In [32]:
df.isnull().sum()


longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [33]:
# Question 4
# How many unique values does the ocean_proximity column have?

In [34]:
df['ocean_proximity'].nunique()

5

In [35]:
# Question 5
# What's the average value of the median_house_value for the houses located near the bay?

In [36]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [37]:
near_the_bay_houses_average = df.groupby('ocean_proximity').median_house_value.mean()
output = near_the_bay_houses_average['NEAR BAY']
output

259212.31179039303

In [38]:
# Question 6
# Calculate the average of total_bedrooms column in the dataset.
# Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
# Now, calculate the average of total_bedrooms again.
# Has it changed?

In [39]:
before = df['total_bedrooms'].mean()
before

537.8705525375618

In [40]:
df_with_replacements = df.copy()
df_with_replacements['total_bedrooms']= df_with_replacements['total_bedrooms'].fillna(output)
print(df_with_replacements.info())
after = df_with_replacements['total_bedrooms'].mean()
after

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB
None


3132.134570766054

In [41]:
# Question 7

In [42]:
# Select all the options located on islands.
# Select only columns housing_median_age, total_rooms, total_bedrooms.

subset_islands = df_with_replacements[df_with_replacements['ocean_proximity'] == 'ISLAND']
subset_islands = subset_islands[['housing_median_age', 'total_rooms', 'total_bedrooms']]
subset_islands.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [43]:
# Get the underlying NumPy array. Let's call it X.

X = subset_islands.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [44]:
# Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.

X_transposed = X.T
X_transposed

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [45]:
XTX = X_transposed.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [46]:
# Compute the inverse of XTX.

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [47]:
# Create an array y with values [950, 1300, 800, 1000, 1300].

y = np.array([950, 1300, 800, 1000, 1300])

In [48]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the value of the last element of w?

before_w = XTX_inv.dot(X_transposed)
w = before_w.dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])